ui: mocha-bdd
html: test/fixture.html
browsers:
  - name: chrome
    version: -1..latest
  - name: firefox
    version: -1..latest
  - name: safari
    version: -1..latest
  - name: ie
    version: 9..latest
